config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    resources :purchases
  end
  root 'users#main_page'
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :purchases, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :name, :icon, presence: true

  def total_amount
    total = 0
    purchases.each do |purchase|
      total += purchase.amount
    end
    total
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  authorize_resource

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon).merge(author_id: current_user.id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def list_icons
    [
      ['Air Travel', 'air-travel.png'],
      ['Animals', 'animals.png'],
      ['Art', 'art.png'],
      ['Books', 'books.png'],
      ['Business', 'business.png'],
      ['Chemistry', 'chemistry.png'],
      ['Delivery', 'delivery.png'],
      ['Education', 'education.png'],
      ['Entertaining', 'entertaining.png'],
      ['Farming', 'farming.png'],
      ['Food', 'food.png'],
      ['Furniture', 'furniture.png'],
      ['Healthcare', 'healthcare.png'],
      ['Land travel', 'land-travel.png'],
      ['Sports', 'sports.png'],
      ['Technology', 'technology.png'],
      ['Toys', 'toys.png'],
      ['Transportation', 'transportation.png'],
      ['Vacations', 'vacations.png'],
      ['Videogames', 'videogames.png']
    ]
  end
end

app/views/groups/_button.html.erb
<div class="bg-second py-8 absolute inset-x-0 bottom-0 text-center">
    <div class="container mx-auto">
      <%= link_to 'ADD NEW CATEGORY', new_group_path, class: "text-center text-white py-4 px-24
     font-proxima border-2 border-bg-white rounded-lg cursor-pointer" %>
    </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: @group) do |form| %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name",
    class: "py-3 px-4 border border-bg-darktext w-full font-proxima font-normal" %>
  </div>

  <div class="field">
    <%= form.select(:icon, options_for_select(list_icons), {} ,
    { class: "py-3 px-4 border border-bg-darktext w-full font-proxima font-normal bg-white" }) %>
  </div>
  
  <% if group.errors.any? %>
  <div class="bg-white border border-teal-500 rounded text-teal-900 px-4 py-3 shadow-md w-50" role="alert">
    <div class="flex">
      <div class="py-1 text-red-500"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
      <div>
        <h2 class="text-red-500"><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
        <ul class="list-disc">
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <% end %>

  <div class="bg-second py-4 absolute inset-x-0 bottom-0 text-center">
    <%= form.submit 'ADD CATEGORY', class: "bg-transparent text-center text-white py-4 px-24
     font-proxima border-2 border-bg-white rounded-lg cursor-pointer" %>
  </div>

<% end %>

app/views/groups/_group.html.erb
<%= link_to group_purchases_path(group) do%>
    <li class="grid grid-cols-6 bg-white space-x-2 p-2 border border-gray-200 mb-2">
    <div class="text-center image">
        <%= image_tag("#{group.icon}", :alt => "group icon") %>
    </div>
    <div class="col-start-2 col-span-4 text-gray-400 font-proxima">
        <%= group.name %>
    </div>
    <div class="">
        <p class="font-bold font-proxima">$<%= group.total_amount %></p>
    </div>
    </li>
<%end%>

app/views/groups/_nav.html.erb
<nav class="bg-main py-4 px-4">
    <ul class="flex justify-between items-center container mx-auto">
      <li>
        <%= link_to root_path do %>
        <i class="fa fa-arrow-left text-white cursor-pointer"></i>
        <%end%>
      </li>
      <li>
        <p class="text-white font-proxima">CATEGORY</p>
      </li>
      <li>
        <i class="fa fa-search text-white cursor-pointer"></i>
      </li>
    </ul>
  </nav>

app/views/groups/edit.html.erb
<section class="h-screen bg-back relative">
    <nav class="bg-main py-4 px-4">
        <ul class="flex justify-between items-center">
          <li>
            <%= link_to groups_path do %>
            <i class="fa fa-arrow-left text-white cursor-pointer"></i>
            <%end%>
          </li>
          <li>
            <p class="text-white font-proxima">EDIT CATEGORY</p>
          </li>
          <li>
            <%= link_to groups_path do %>
            <i class="fa fa-bars text-white cursor-pointer"></i>
            <%end%>
          </li>
        </ul>
    </nav>
    
    <%= render 'form', group: @group %>
</section>

app/views/groups/index.html.erb
<section class="h-screen bg-back relative">

  <%= render "notice/notice" %>
  <%= render "groups/nav" %>
  <ul class="w-full px-4 mt-2 overflow-auto sm:px-0 container mx-auto">
    <%= render @groups %>
  </ul>
  <%= render "groups/button" %>
</section>

app/views/groups/new.html.erb
<section class="h-screen bg-back relative">
    <nav class="bg-main py-4 px-4">
        <ul class="flex justify-between items-center">
          <li>
            <%= link_to groups_path do %>
            <i class="fa fa-arrow-left text-white cursor-pointer"></i>
            <%end%>
          </li>
          <li>
            <p class="text-white font-proxima">NEW CATEGORY</p>
          </li>
          <li>
            <%= link_to groups_path do %>
            <i class="fa fa-bars text-white cursor-pointer"></i>
            <%end%>
          </li>
        </ul>
    </nav>
    
    <%= render 'form', group: @group %>
</section>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<section class="h-screen bg-back relative">

  <nav class="bg-main py-4 px-4">
    <ul class="flex justify-between items-center">
      <li>
        <%= link_to groups_path do %>
        <i class="fa fa-arrow-left text-white cursor-pointer"></i>
        <%end%>
      </li>
      <li>
        <p class="text-white font-proxima">DETAILS CATEGORY</p>
      </li>
      <li>
        <i class="fa fa-bars text-transparent cursor-pointer"></i>
      </li>
    </ul>
  </nav>

  <div class="w-full px-4 mt-4">
    <div class="p-4 space-y-4 bg-white rounded">
      <img src=<% @group.icon %> alt="group-picture">
      <h2 class="font-bold font-proxima"><%= @group.name %></h2>
      <p class="font-proxima"><%= @group.total_amount %> unit</p>
      <div class="font-proxima">     
        <%= link_to 'Edit', edit_group_path(@group), class: 'text-white py-2 px-8
        border-2 bg-second rounded-lg cursor-pointer' %>
      </div>
    </div>
  </div>
</section>